import './globals.css';

import clsx from 'clsx';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: [
    {
      path:   '../../public/fonts/Pretendard-Regular.woff2',
      weight: '400',
      style:  'normal',
    },
    {
      path:   '../../public/fonts/Pretendard-Medium.woff2',
      weight: '500',
      style:  'normal',
    },
    {
      path:   '../../public/fonts/Pretendard-SemiBold.woff2',
      weight: '600',
      style:  'normal',
    },
  ],
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title:       'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(pretendard.variable, 'bg-grayscale-800')} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
